openapi: 3.0.3
info:
  title: AI Cover Generator API
  description: API for generating AI-powered covers for social media platforms
  version: 1.0.0

servers:
  - url: https://ai-cover-generator.vercel.app/api
    description: Production server
  - url: http://localhost:3000/api
    description: Development server

paths:
  /generate:
    post:
      summary: Generate covers from text
      description: Submits text content and generates covers for selected platforms
      tags:
        - Generation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateRequest"
      responses:
        "200":
          description: Generation job created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /generate/{jobId}:
    get:
      summary: Get generation job status
      description: Retrieves the current status and results of a generation job
      tags:
        - Generation
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Job status retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobStatus"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /templates:
    get:
      summary: List available templates
      description: Retrieves all available cover templates
      tags:
        - Templates
      parameters:
        - name: platform
          in: query
          schema:
            type: string
            enum: [xiaohongshu, wechat, product, custom]
          description: Filter by platform
        - name: category
          in: query
          schema:
            type: string
          description: Filter by category
      responses:
        "200":
          description: Templates retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      $ref: "#/components/schemas/Template"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /templates/{templateId}:
    get:
      summary: Get template details
      description: Retrieves detailed information about a specific template
      tags:
        - Templates
      parameters:
        - name: templateId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Template retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateDetail"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /analyze:
    post:
      summary: Analyze text content
      description: Pre-analyzes text to extract title and key points without generating images
      tags:
        - Analysis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  minLength: 1
                  maxLength: 5000
                contentType:
                  type: string
                  enum: [title, paragraph, article, blog]
              required:
                - text
                - contentType
      responses:
        "200":
          description: Text analyzed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentAnalysis"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /styles:
    get:
      summary: List available styles
      description: Retrieves all available cover styles
      tags:
        - Styles
      responses:
        "200":
          description: Styles retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  styles:
                    type: array
                    items:
                      $ref: "#/components/schemas/Style"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /health:
    get:
      summary: Health check
      description: Checks if the API is healthy
      tags:
        - System
      responses:
        "200":
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string

components:
  schemas:
    GenerateRequest:
      type: object
      properties:
        text:
          type: string
          minLength: 1
          maxLength: 5000
          description: The text content to generate covers from
        contentType:
          type: string
          enum: [title, paragraph, article, blog]
          description: Type of content being provided
        selectedStyle:
          type: string
          description: ID of the selected style
        targetPlatforms:
          type: array
          items:
            type: string
            enum: [xiaohongshu, wechat, product, custom]
          minItems: 1
          description: Target platforms for cover generation
        options:
          type: object
          properties:
            infiniteCanvas:
              type: boolean
              default: false
              description: Enable infinite canvas mode
            customColors:
              type: array
              items:
                type: string
                pattern: "^#[0-9A-Fa-f]{6}$"
              description: Custom color palette
      required:
        - text
        - contentType
        - selectedStyle
        - targetPlatforms

    GenerateResponse:
      type: object
      properties:
        jobId:
          type: string
          format: uuid
          description: ID of the generation job
        estimatedTime:
          type: integer
          description: Estimated time in seconds
        status:
          type: string
          enum: [pending, processing]
          description: Initial status of the job

    JobStatus:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, processing, completed, failed]
        progress:
          type: number
          minimum: 0
          maximum: 100
          description: Progress percentage (0-100)
        currentStep:
          type: string
          description: Current processing step
        result:
          $ref: "#/components/schemas/GenerationResult"
        error:
          $ref: "#/components/schemas/Error"
        createdAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
        processingTimeMs:
          type: integer
          description: Total processing time in milliseconds

    GenerationResult:
      type: object
      properties:
        covers:
          type: array
          items:
            $ref: "#/components/schemas/GeneratedCover"
        analysis:
          $ref: "#/components/schemas/ContentAnalysis"
        editableContent:
          type: object
          properties:
            title:
              type: string
            subtitle:
              type: string
            keyPoints:
              type: array
              items:
                type: string

    GeneratedCover:
      type: object
      properties:
        id:
          type: string
          format: uuid
        platform:
          type: string
          enum: [xiaohongshu, wechat, product, custom]
        imageUrl:
          type: string
          format: uri
        thumbnailUrl:
          type: string
          format: uri
        templateUsed:
          type: string
        metadata:
          type: object
          properties:
            width:
              type: integer
            height:
              type: integer
            fileSize:
              type: integer
            format:
              type: string

    ContentAnalysis:
      type: object
      properties:
        originalText:
          type: string
        extractedTitle:
          type: string
        keyPoints:
          type: array
          items:
            type: string
        suggestedTags:
          type: array
          items:
            type: string
        contentSummary:
          type: string
        visualConcept:
          type: object
          properties:
            mood:
              type: string
            style:
              type: string
            colorPalette:
              type: array
              items:
                type: string
            composition:
              type: string

    Template:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        category:
          type: string
        platform:
          type: string
          enum: [xiaohongshu, wechat, product, custom]
        aspectRatio:
          type: string
        preview:
          type: string
          format: uri
        isPremium:
          type: boolean
          default: false

    TemplateDetail:
      allOf:
        - $ref: "#/components/schemas/Template"
        - type: object
          properties:
            elements:
              type: array
              items:
                $ref: "#/components/schemas/TemplateElement"
            constraints:
              $ref: "#/components/schemas/TemplateConstraints"

    TemplateElement:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [title, subtitle, background, decoration, logo]
        position:
          $ref: "#/components/schemas/Position"
        style:
          type: object
          properties:
            fontFamily:
              type: string
            fontSize:
              type: integer
            fontWeight:
              type: string
            color:
              type: string
            backgroundColor:
              type: string
        dynamic:
          type: boolean
          description: Whether content is injected dynamically

    TemplateConstraints:
      type: object
      properties:
        maxTextLength:
          type: integer
        allowedFonts:
          type: array
          items:
            type: string
        colorScheme:
          type: array
          items:
            type: string
        layoutRules:
          type: array
          items:
            type: string

    Position:
      type: object
      properties:
        x:
          type: number
          minimum: 0
        y:
          type: number
          minimum: 0
        width:
          type: number
          minimum: 0
        height:
          type: number
          minimum: 0
      required:
        - x
        - y

    Style:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        preview:
          type: string
          format: uri
        mood:
          type: string
        colorPalette:
          type: array
          items:
            type: string
        isDefault:
          type: boolean
          default: false

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
        retryable:
          type: boolean
        provider:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: "#/components/schemas/Error"
            required:
              - error

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: NOT_FOUND
                  message:
                    type: string
                    example: The requested resource was not found

    TooManyRequests:
      description: Too many requests
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: TOO_MANY_REQUESTS
                  message:
                    type: string
                    example: Rate limit exceeded
                  retryAfter:
                    type: integer
                    description: Seconds to wait before retrying

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: INTERNAL_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []